pipeline {
    agent any

    stages {
         stage('Prepare') {
            steps {
                // Define the label for the Windows agent
                script {
                    agentLabel = ' LinuxNode-ProdServer'
                }
                sh 'pwd'
                sh "ls"
                stash name: 'build-artifacts', includes: '**/*', excludes: 'workspace**'                
            }
        }
        stage('Package Install') {
            agent {                
                label agentLabel
            }
            options {
                skipDefaultCheckout true
            }
            steps {
                
               
                 dir("workspace"){
                    unstash 'build-artifacts'
					sh "ls"
					sh 'pwd'
                   
                   sh 'sudo su'
                   sh 'node --version'
					         //sh 'npm install --legacy-peer-deps'    
                    
                     
                   
                 }
            }
        }
    }
}
